name: debbie_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  timezone: ^0.10.1
  flutter_local_notifications: ^19.4.0
  connectivity_plus: ^5.0.1
  csv: ^5.0.2
  fl_chart: ^0.65.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/xtrackr.png
    - assets/images/profile_avatar.png
