// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq0xgB7_3PkdjF1FVeN0kJ8a2C2KNKmnk',
    appId: '1:334122075796:web:93ec9426e1fc1b8b035681',
    messagingSenderId: '334122075796',
    projectId: 'debbie-expense',
    authDomain: 'debbie-expense.firebaseapp.com',
    storageBucket: 'debbie-expense.firebasestorage.app',
    measurementId: 'G-2Y39CTQ80E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ltBRDtgUXemhwE_4JCfb79TXgaibKY4',
    appId: '1:334122075796:android:64b97ce081387273035681',
    messagingSenderId: '334122075796',
    projectId: 'debbie-expense',
    storageBucket: 'debbie-expense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzW45wq8ur3HhTr4tpY6Pxymy0lhOu_Po',
    appId: '1:334122075796:ios:b6112aee2495e20e035681',
    messagingSenderId: '334122075796',
    projectId: 'debbie-expense',
    storageBucket: 'debbie-expense.firebasestorage.app',
    iosBundleId: 'com.example.debbieProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzW45wq8ur3HhTr4tpY6Pxymy0lhOu_Po',
    appId: '1:334122075796:ios:b6112aee2495e20e035681',
    messagingSenderId: '334122075796',
    projectId: 'debbie-expense',
    storageBucket: 'debbie-expense.firebasestorage.app',
    iosBundleId: 'com.example.debbieProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq0xgB7_3PkdjF1FVeN0kJ8a2C2KNKmnk',
    appId: '1:334122075796:web:08098e2ac2c27274035681',
    messagingSenderId: '334122075796',
    projectId: 'debbie-expense',
    authDomain: 'debbie-expense.firebaseapp.com',
    storageBucket: 'debbie-expense.firebasestorage.app',
    measurementId: 'G-C4TBWH9QJH',
  );
}
